-- ============================================================================
-- 2026-09-13 — lamap-db: pin search_path on 140 SECURITY DEFINER functions (hardening, zero behaviour change)
-- ============================================================================
-- WHAT: ALTER FUNCTION ... SET search_path = <path>. Metadata only: no data, table, view, grant or function
-- body is touched. Reversible instantly: 2026-09-13_lamap_db_search_path_pinning_ROLLBACK.sql
-- (RESET search_path; prior proconfig saved in lamap-db backup.search_path_pin_20260913).
--
-- WHY: SECURITY DEFINER functions without a fixed search_path resolve unqualified names through the
-- CALLER's path (search_path hijack class). Low severity today (anon/authenticated cannot create objects
-- anywhere), but it is the scanner finding on the Lamap repo.
--
-- HOW EQUIVALENCE WAS PROVEN (before applying):
--  1. Static: every unqualified identifier/operator of each function AND of everything that runs under it
--     (unpinned callees, trigger functions of tables it touches, policy/default expressions) was resolved
--     against the live catalog under every real caller path: PostgREST RPC per exposed schema
--     (<schema>, public, extensions | <schema>, public), cron/postgres (public, extensions), anon/authenticated
--     direct (public — their role path names schema silver, which no longer exists), supabase_admin
--     (public, auth, extensions). Functions whose names resolve to different schemas depending on the
--     caller were EXCLUDED (behaviour already caller-dependent), as were functions that create objects
--     unqualified, touch search_path, or execute caller-supplied SQL.
--  2. PostgreSQL itself, in rolled-back transactions: plpgsql_check dependency sets (92 PL/pgSQL functions
--     with dependencies) and BEGIN ATOMIC recompilation with pg_depend bindings (49 SQL functions) —
--     pinned path vs website path vs direct path: 0 differences, 0 new errors, 0 compile failures.
--  3. Live outputs: md5 of the results of all 22 argument-free STABLE functions, called as role anon with the
--     PostgREST path, in READ ONLY transactions — identical twice before, identical after.
--  4. Live PostgREST calls after applying (public, lamap_app): HTTP 200.
--  Overhead of the SET clause measured at ~0.3 µs per call; the only per-row use (policy on
--  entity_functions) is on a 0-row table.
--
-- NOT PINNED (left exactly as they were):
--   ask_lamap.execute_query(query_text text): runs caller-supplied SQL; resolution depends on the caller
--   lamap_app.get_property_categories(p_commune text, p_canton text): ambiguous: categories[rel]->['content_sites', 'lamap_app', 'public']
--   lamap_app.get_building_typologies(p_commune text, p_canton text): ambiguous: typologies[rel]->['ask_lamap', 'public']
--   lamap_app.calculate_rental_estimation(p_user_id uuid, p_property_type text, p_property_subtype_id uuid, p_commune text, p_npa text, p_surface_m2 numeric, p_selected_feature_ids uuid[], p_address_id uuid, p_plot_id uuid, p_street_name text, p_street_number text, p_num_rooms numeric, p_num_bedrooms integer, p_num_bathrooms integer, p_construction_year integer, p_user_notes text, p_unit_id uuid, p_base_rent numeric): ambiguous: user_notes[rel]->['lamap_app', 'public']
--   lamap_app.calculate_rental_estimation(p_user_id uuid, p_property_type text, p_property_subtype_id uuid, p_commune text, p_npa text, p_surface_m2 numeric, p_selected_feature_ids uuid[], p_address_id uuid, p_plot_id uuid, p_street_name text, p_street_number text, p_num_rooms numeric, p_num_bedrooms integer, p_num_bathrooms integer, p_construction_year integer, p_user_notes text, p_unit_id uuid, p_base_rent numeric, p_latitude numeric, p_longitude numeric): ambiguous: user_notes[rel]->['lamap_app', 'public']
--   lamap_app.calculate_estimation_national(p_user_id uuid, p_property_type text, p_property_subtype_id uuid, p_commune text, p_canton text, p_npa text, p_surface_m2 numeric, p_selected_feature_ids uuid[], p_address_id uuid, p_plot_id uuid, p_street_name text, p_street_number text, p_num_rooms numeric, p_num_bathrooms integer, p_construction_year integer, p_user_notes text): ambiguous: user_notes[rel]->['lamap_app', 'public']
--   lamap_app.calculate_rental_estimation(p_user_id uuid, p_property_type text, p_property_subtype_id uuid, p_commune text, p_npa text, p_surface_m2 numeric, p_selected_feature_ids uuid[], p_address_id uuid, p_plot_id uuid, p_street_name text, p_street_number text, p_num_rooms numeric, p_num_bedrooms integer, p_num_bathrooms integer, p_construction_year integer, p_user_notes text, p_unit_id uuid, p_base_rent numeric, p_latitude numeric, p_longitude numeric, p_no_commune_no_parcelle text): ambiguous: user_notes[rel]->['lamap_app', 'public']
--   lamap_app.generate_watchlist_notifications(): ambiguous: sad[rel]->['ask_lamap', 'public']
--   lamap_app.scan_keywords_for_matches(): ambiguous: unaccent[func]->['ask_lamap', 'public']
--   public.content_insert_article(p_site text, p_title text, p_slug text, p_excerpt text, p_body_html text, p_focus_keyphrase text, p_seo_title text, p_seo_description text, p_topic_seed text, p_references_used jsonb, p_category_slug text, p_tags text[], p_reading_time integer): ambiguous: tags[rel]->['content_sites', 'lamap_app', 'public']
--   public.add_keyword(p_keyword text, p_search_transactions_acheteur boolean, p_search_transactions_vendeur boolean, p_search_sad_mandataire boolean, p_search_sad_proprietaire boolean, p_search_entities boolean, p_auto_add_to_watchlist boolean, p_notify_email boolean, p_notify_app boolean, p_notes text): ambiguous: unaccent[func]->['ask_lamap', 'public']
--   public.content_insert_article(p_site text, p_title text, p_slug text, p_excerpt text, p_body_html text, p_focus_keyphrase text, p_seo_title text, p_seo_description text, p_topic_seed text, p_references_used jsonb, p_category_slug text, p_tags text[], p_reading_time integer, p_og_image_url text): ambiguous: tags[rel]->['content_sites', 'lamap_app', 'public']
--   public.exec_sql(query text): runs caller-supplied SQL; resolution depends on the caller
--   (5 functions pinned earlier today in 2026-09-13_alert_triage_fixes.sql re-verified with the same method.)
-- ============================================================================
BEGIN;
SET LOCAL lock_timeout = '5s';
CREATE TABLE IF NOT EXISTS backup.search_path_pin_20260913 (fn_oid oid, signature text, proconfig_before text[], pinned_path text, applied_at timestamptz DEFAULT now());
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16615, 'admin_readonly.refresh_admin_views()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION admin_readonly.refresh_admin_views() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16623, 'ask_lamap.entity_intelligence(text,text,integer)', NULL, 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION ask_lamap.entity_intelligence(text,text,integer) SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16625, 'ask_lamap.find_comparables(text,numeric,integer,integer,numeric)', NULL, 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION ask_lamap.find_comparables(text,numeric,integer,integer,numeric) SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16626, 'ask_lamap.find_opportunities(text,integer,integer)', NULL, 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION ask_lamap.find_opportunities(text,integer,integer) SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16627, 'ask_lamap.get_schema_info()', NULL, 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION ask_lamap.get_schema_info() SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16628, 'ask_lamap.get_table_columns(text)', NULL, 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION ask_lamap.get_table_columns(text) SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16629, 'ask_lamap.get_user_context(uuid)', NULL, 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION ask_lamap.get_user_context(uuid) SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16630, 'ask_lamap.property_dossier(text)', NULL, 'public, extensions, ask_lamap, storage, pg_temp'); ALTER FUNCTION ask_lamap.property_dossier(text) SET search_path = public, extensions, ask_lamap, storage, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16838, 'lamap_app.add_keyword(text,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.add_keyword(text,boolean,boolean,boolean,boolean,boolean,boolean,boolean,boolean,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16839, 'lamap_app.add_to_watchlist(text,text,text,jsonb,boolean,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.add_to_watchlist(text,text,text,jsonb,boolean,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16841, 'lamap_app.archive_notification(uuid)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.archive_notification(uuid) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16843, 'lamap_app.bulk_add_tags_to_watchlist(uuid[],uuid[])', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.bulk_add_tags_to_watchlist(uuid[],uuid[]) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16844, 'lamap_app.bulk_add_to_watchlist(jsonb)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.bulk_add_to_watchlist(jsonb) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16875, 'lamap_app.export_selected_plots_csv(text[])', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.export_selected_plots_csv(text[]) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16876, 'lamap_app.export_watchlist_plots_csv(uuid,uuid)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.export_watchlist_plots_csv(uuid,uuid) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16885, 'lamap_app.get_age_distribution(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_age_distribution(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16886, 'lamap_app.get_age_distribution_cached(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_age_distribution_cached(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16892, 'lamap_app.get_commune_index_overview()', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_commune_index_overview() SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16904, 'lamap_app.get_market_concentration(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_market_concentration(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16905, 'lamap_app.get_market_concentration_cached(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_market_concentration_cached(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16906, 'lamap_app.get_monthly_transaction_count(integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_monthly_transaction_count(integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16907, 'lamap_app.get_monthly_transaction_volume(integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_monthly_transaction_volume(integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16908, 'lamap_app.get_owner_analytics_kpis(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_owner_analytics_kpis(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16909, 'lamap_app.get_owner_analytics_kpis_cached(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_owner_analytics_kpis_cached(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16910, 'lamap_app.get_owner_type_distribution(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_owner_type_distribution(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16911, 'lamap_app.get_owner_type_distribution_cached(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_owner_type_distribution_cached(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16912, 'lamap_app.get_owner_type_distribution_granular(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_owner_type_distribution_granular(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16913, 'lamap_app.get_parcelle_notes(uuid,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_parcelle_notes(uuid,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16914, 'lamap_app.get_parcelle_notes_count(uuid,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_parcelle_notes_count(uuid,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16922, 'lamap_app.get_property_distribution(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_property_distribution(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16923, 'lamap_app.get_property_distribution_cached(text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_property_distribution_cached(text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16932, 'lamap_app.get_top_buyers(integer,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_buyers(integer,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16933, 'lamap_app.get_top_owners_by_parcels(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_by_parcels(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16934, 'lamap_app.get_top_owners_by_parcels_cached(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_by_parcels_cached(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16935, 'lamap_app.get_top_owners_by_surface(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_by_surface(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16936, 'lamap_app.get_top_owners_by_surface_cached(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_by_surface_cached(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16937, 'lamap_app.get_top_owners_commercial(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_commercial(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16938, 'lamap_app.get_top_owners_commercial_cached(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_commercial_cached(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16939, 'lamap_app.get_top_owners_residential(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_residential(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16940, 'lamap_app.get_top_owners_residential_cached(text,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_owners_residential_cached(text,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16941, 'lamap_app.get_top_transactions(integer,integer)', NULL, 'public, extensions, ask_lamap, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_top_transactions(integer,integer) SET search_path = public, extensions, ask_lamap, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16942, 'lamap_app.get_transactions_by_commune(integer,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_transactions_by_commune(integer,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16947, 'lamap_app.get_unread_count()', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_unread_count() SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16948, 'lamap_app.get_user_keywords()', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_user_keywords() SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16949, 'lamap_app.get_user_notifications(integer,integer,boolean,uuid)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_user_notifications(integer,integer,boolean,uuid) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16951, 'lamap_app.get_volume_by_commune(integer,integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_volume_by_commune(integer,integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16952, 'lamap_app.get_volume_by_typology(integer)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_volume_by_typology(integer) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16956, 'lamap_app.is_watched(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.is_watched(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16958, 'lamap_app.mark_all_notifications_read(uuid)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.mark_all_notifications_read(uuid) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16959, 'lamap_app.mark_notification_read(uuid)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.mark_notification_read(uuid) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16969, 'lamap_app.notify_bug_report()', NULL, 'public, extensions, auth, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.notify_bug_report() SET search_path = public, extensions, auth, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16978, 'lamap_app.remove_from_watchlist(uuid)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.remove_from_watchlist(uuid) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16980, 'lamap_app.set_bug_report_user_id()', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.set_bug_report_user_id() SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (16990, 'lamap_app.update_watchlist_item(uuid,boolean,text,text,boolean,boolean)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.update_watchlist_item(uuid,boolean,text,text,boolean,boolean) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17164, 'backfill_link_plot_transactions()', '{statement_timeout=5min}', 'public, extensions, pg_temp'); ALTER FUNCTION backfill_link_plot_transactions() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17198, 'capture_plot_ownership_snapshot()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION capture_plot_ownership_snapshot() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17199, 'capture_sad_status_snapshot()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION capture_sad_status_snapshot() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17200, 'cascade_master_access()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION cascade_master_access() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17223, 'content_get_last_refs(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION content_get_last_refs(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17224, 'content_get_reference_pages()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION content_get_reference_pages() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17225, 'content_get_site_config(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION content_get_site_config(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17226, 'content_get_used_topics(text,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION content_get_used_topics(text,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17229, 'content_update_article_image(uuid,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION content_update_article_image(uuid,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17242, 'current_user_entity_id()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION current_user_entity_id() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17304, 'enforce_product_prerequisite()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION enforce_product_prerequisite() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17310, 'expire_ended_subscriptions()', '{statement_timeout=30s}', 'public, extensions, pg_temp'); ALTER FUNCTION expire_ended_subscriptions() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17313, 'expire_stale_access()', '{statement_timeout=120s}', 'public, extensions, pg_temp'); ALTER FUNCTION expire_stale_access() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17327, 'fix_null_auth_tokens()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION fix_null_auth_tokens() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17441, 'get_age_distribution_cached(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_age_distribution_cached(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17442, 'get_agencies_by_commune(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_agencies_by_commune(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17443, 'get_agency_communes_from_transactions()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_agency_communes_from_transactions() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17474, 'get_commercial_transactions_monthly(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_commercial_transactions_monthly(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17478, 'get_commune_index_overview()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_commune_index_overview() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17542, 'get_lamap_hubspot_sync_source()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_lamap_hubspot_sync_source() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17552, 'get_mapchat_market_indicator(uuid)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_mapchat_market_indicator(uuid) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17553, 'get_market_concentration_cached(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_market_concentration_cached(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17555, 'get_monthly_transaction_count(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_monthly_transaction_count(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17556, 'get_monthly_transaction_volume(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_monthly_transaction_volume(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17566, 'get_owner_analytics_kpis_cached(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_owner_analytics_kpis_cached(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17570, 'get_owner_type_distribution_cached(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_owner_type_distribution_cached(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17571, 'get_owner_type_distribution_granular(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_owner_type_distribution_granular(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17663, 'get_property_distribution_cached(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_property_distribution_cached(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17691, 'get_residential_transactions_monthly(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_residential_transactions_monthly(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17698, 'get_sad_market_kpis(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_sad_market_kpis(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17700, 'get_sad_permits_by_commune(integer,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_sad_permits_by_commune(integer,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17701, 'get_sad_permits_by_typology(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_sad_permits_by_typology(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17713, 'get_table_health(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_table_health(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17714, 'get_top_agencies_by_commune(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_agencies_by_commune(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17715, 'get_top_agents_by_commune(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_agents_by_commune(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17716, 'get_top_buyers(integer,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_buyers(integer,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17718, 'get_top_owners_by_parcels_cached(text,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_owners_by_parcels_cached(text,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17719, 'get_top_owners_by_surface_cached(text,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_owners_by_surface_cached(text,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17720, 'get_top_owners_commercial_cached(text,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_owners_commercial_cached(text,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17721, 'get_top_owners_residential_cached(text,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_owners_residential_cached(text,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17722, 'get_top_transactions(integer,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_top_transactions(integer,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17726, 'get_transactions_by_commune(integer,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_transactions_by_commune(integer,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17728, 'get_transactions_by_typology(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_transactions_by_typology(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17733, 'get_transactions_market_kpis(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_transactions_market_kpis(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17741, 'get_user_keywords()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_user_keywords() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17749, 'get_verified_transactions_by_commune(text,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_verified_transactions_by_commune(text,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17751, 'get_volume_by_commune(integer,integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_volume_by_commune(integer,integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17752, 'get_volume_by_typology(integer)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_volume_by_typology(integer) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17755, 'get_weekly_top_transactions(date)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_weekly_top_transactions(date) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17764, 'grant_product_access(text,text,text,integer,text)', NULL, 'public, extensions, auth, pg_temp'); ALTER FUNCTION grant_product_access(text,text,text,integer,text) SET search_path = public, extensions, auth, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17782, 'has_product_access(text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION has_product_access(text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17804, 'inherit_master_access()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION inherit_master_access() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17805, 'insert_bug_report(text,text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION insert_bug_report(text,text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17851, 'normalize_phone_number()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION normalize_phone_number() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17947, 'rebuild_transactions_fao_from_mv()', '{statement_timeout=600s}', 'public, extensions, ask_lamap, pg_temp'); ALTER FUNCTION rebuild_transactions_fao_from_mv() SET search_path = public, extensions, ask_lamap, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (17999, 'refresh_owner_analytics_cache()', '{statement_timeout=300s}', 'public, extensions, pg_temp'); ALTER FUNCTION refresh_owner_analytics_cache() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18044, 'refresh_tx_autocomplete_matviews()', '{statement_timeout=5min}', 'public, extensions, pg_temp'); ALTER FUNCTION refresh_tx_autocomplete_matviews() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18058, 'remove_keyword(uuid)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION remove_keyword(uuid) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18065, 'revoke_product_access(text,text,text)', NULL, 'public, extensions, auth, pg_temp'); ALTER FUNCTION revoke_product_access(text,text,text) SET search_path = public, extensions, auth, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18547, 'submit_contact_message(text,text,text,text)', NULL, 'public, extensions, auth, pg_temp'); ALTER FUNCTION submit_contact_message(text,text,text,text) SET search_path = public, extensions, auth, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18558, 'sync_phone_columns()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION sync_phone_columns() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18559, 'sync_plots_constructibility()', '{statement_timeout=900s}', 'public, extensions, pg_temp'); ALTER FUNCTION sync_plots_constructibility() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18566, 'sync_user_alerts_to_lamap_app()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION sync_user_alerts_to_lamap_app() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18569, 'track_event(text,text,text,text,text,text,text,jsonb,integer,integer,text,text,integer,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION track_event(text,text,text,text,text,text,text,jsonb,integer,integer,text,text,integer,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18597, 'update_keyword(uuid,boolean,boolean,boolean,boolean,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION update_keyword(uuid,boolean,boolean,boolean,boolean,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (18603, 'update_plot_npas_ge()', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION update_plot_npas_ge() SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80320566, 'get_plots_filtered(integer,integer[],integer,numeric,numeric,boolean,boolean,boolean,boolean,text,text,text,text,boolean,numeric,numeric,text,text,text,text,integer,integer,numeric,numeric,integer,integer,integer,integer,text,numeric,numeric,text,date,date,numeric,numeric,date,text,text,date,date,text,date,boolean,integer,integer,integer,double precision,double precision,integer,integer,integer,integer,integer,integer,text,numeric,numeric,numeric,numeric,numeric,text,text,boolean,boolean,uuid)', '{statement_timeout=60s,plan_cache_mode=force_custom_plan}', 'public, extensions, pg_temp'); ALTER FUNCTION get_plots_filtered(integer,integer[],integer,numeric,numeric,boolean,boolean,boolean,boolean,text,text,text,text,boolean,numeric,numeric,text,text,text,text,integer,integer,numeric,numeric,integer,integer,integer,integer,text,numeric,numeric,text,date,date,numeric,numeric,date,text,text,date,date,text,date,boolean,integer,integer,integer,double precision,double precision,integer,integer,integer,integer,integer,integer,text,numeric,numeric,numeric,numeric,numeric,text,text,boolean,boolean,uuid) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783831, 'lamap_app.get_parcelles_batiments_kpis(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_parcelles_batiments_kpis(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783833, 'lamap_app.get_dwellings_distribution(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_dwellings_distribution(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783834, 'lamap_app.get_floors_distribution(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_floors_distribution(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783835, 'lamap_app.get_land_use_distribution(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_land_use_distribution(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783836, 'lamap_app.get_construction_periods(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_construction_periods(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783837, 'lamap_app.get_pool_distribution(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_pool_distribution(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783838, 'lamap_app.get_ppe_distribution(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_ppe_distribution(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783840, 'lamap_app.get_volume_distribution(text,text)', NULL, 'public, extensions, lamap_app, pg_temp'); ALTER FUNCTION lamap_app.get_volume_distribution(text,text) SET search_path = public, extensions, lamap_app, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783841, 'get_parcelles_batiments_kpis(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_parcelles_batiments_kpis(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783842, 'get_property_categories(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_property_categories(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783843, 'get_dwellings_distribution(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_dwellings_distribution(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783844, 'get_floors_distribution(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_floors_distribution(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783845, 'get_land_use_distribution(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_land_use_distribution(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783846, 'get_construction_periods(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_construction_periods(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783847, 'get_pool_distribution(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_pool_distribution(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783848, 'get_ppe_distribution(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_ppe_distribution(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783849, 'get_building_typologies(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_building_typologies(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (80783850, 'get_volume_distribution(text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION get_volume_distribution(text,text) SET search_path = public, extensions, pg_temp;
INSERT INTO backup.search_path_pin_20260913 (fn_oid, signature, proconfig_before, pinned_path) VALUES (84516035, 'calculate_estimation_national(uuid,text,text,text,text,text,numeric,text[],text,text,text,text,text,text)', NULL, 'public, extensions, pg_temp'); ALTER FUNCTION calculate_estimation_national(uuid,text,text,text,text,text,numeric,text[],text,text,text,text,text,text) SET search_path = public, extensions, pg_temp;
COMMIT;
