import json,pathlib,psycopg2,datetime,os,argparse
args=argparse.ArgumentParser();args.add_argument("output",type=pathlib.Path);args=args.parse_args()
with psycopg2.connect(os.environ['DATABASE_URL'],connect_timeout=15) as co:
 with co.cursor() as c:
  c.execute("SET TRANSACTION READ ONLY")
  c.execute("SET LOCAL statement_timeout='60s'")
  c.execute('''WITH s AS MATERIALIZED (select id,label,st_transform(geom,2056) g from bronze_ch.vd_pdcom_sectors where document_id='dd172ee9-e928-5c2f-99d6-3a24eb28cd68'), p AS MATERIALIZED (select egrid,st_transform(st_makevalid(geometry),2056) g from silver_ch.cadastral_plots where commune_bfs=5401 and geometry is not null), pairs AS (select s.id,p.egrid,st_area(st_intersection(s.g,p.g)) a,st_area(p.g) pa,st_area(st_intersection(st_buffer(s.g,-10),p.g)) core_a,st_area(st_intersection(st_buffer(s.g,10),p.g)) expanded_a from s join p on st_dwithin(s.g,p.g,10)) select s.id::text,s.label,st_area(s.g),count(*) filter(where a>0),count(*) filter(where core_a>0),count(*) filter(where expanded_a>0),sum(a),sum(core_a),sum(expanded_a),count(*) filter(where a>0 and a<1),count(*) filter(where a>0 and a/pa<0.01) from s join pairs using(id) group by s.id,s.label,s.g order by s.id''');raw=c.fetchall()
  names=['sector_id','label','sector_area_m2','nominal_pairs','eroded_10m_pairs','expanded_10m_pairs','nominal_overlap_m2','eroded_overlap_m2','expanded_overlap_m2','under_1m2_pairs','under_1pct_pairs'];rows=[dict(zip(names,row)) for row in raw]
  c.execute("select count(*),count(distinct egrid) from silver_ch.cadastral_plots where commune_bfs=5401 and geometry is not null");parcels=c.fetchone()
  c.execute('''WITH fresh AS (select s.id sector_id,p.egrid,st_area(st_intersection(st_transform(s.geom,2056),st_transform(st_makevalid(p.geometry),2056))) a from bronze_ch.vd_pdcom_sectors s join silver_ch.cadastral_plots p on p.commune_bfs=5401 and st_intersects(st_transform(s.geom,2056),st_transform(st_makevalid(p.geometry),2056)) where s.document_id='dd172ee9-e928-5c2f-99d6-3a24eb28cd68'), stored AS (select p.* from bronze_ch.vd_pdcom_parcel_candidates p join bronze_ch.vd_pdcom_sectors s on s.id=p.sector_id where s.document_id='dd172ee9-e928-5c2f-99d6-3a24eb28cd68') select count(*) filter(where f.sector_id is null),count(*) filter(where p.sector_id is null),count(*) filter(where abs(f.a-p.overlap_m2)>0.01),max(abs(f.a-p.overlap_m2)) from (select * from fresh where a>0) f full join stored p using(sector_id,egrid)''');parity=c.fetchone()
report={'checked_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'commune_bfs':5401,'source_parcel_rows':parcels[0],'source_distinct_egrids':parcels[1],'stored_only_pairs':parity[0],'fresh_only_pairs':parity[1],'area_difference_over_0_01m2':parity[2],'max_area_difference_m2':parity[3],'sensitivity_distance_m':10,'interpretation':'Illustrative erosion/dilation sensitivity only; 10m is not an estimated accuracy bound. Counts are sector-parcel pairs, not unique parcels. Every output remains review_required.','sectors':rows}
args.output.write_text(json.dumps(report,indent=2));print(json.dumps({**{k:v for k,v in report.items() if k!='sectors'},'totals':{k:sum(x[k] for x in rows) for k in names[3:]}}))
