themes:
  espace_public:
    - "espace public"
    - "espaces publics"
    - "parc, place"
    - "préau"
    - "terrain de sport"
  patrimoine_bati:
    - "patrimoine"
    - "protection du patrimoine"
    - "patrimoine bâti"
    - "patrimoine bati"
    - "plan de site"
    - "périmètre a"
    - "périmètre b"
    - "planification impérative"
  elements_naturels:
    - "éléments naturels"
    - "elements naturels"
    - "nature"
    - "biodiversité"
    - "biodiversite"
    - "paysage et biodiversité"
    - "continuité biologique"
    - "haies bocagères"
    - "arborisation"
    - "cours d'eau"
    - "bois, forêt"
  mobilite:
    - "mobilité"
    - "mobilite"
    - "transports"
    - "circulation"
    - "piétons"
    - "pietons"
    - "vélos"
    - "velos"
    - "cyclable"
    - "zone 30"
    - "zone de rencontre"
    - "télétransport"
    - "transports publics"
  affectation:
    - "zone d'affectation"
    - "affectation"
    - "zones d'affectation"
    - "zone agricole"
    - "zone de bois"
    - "zone bois"
    - "zone 5"
    - "zone 4"
    - "plan localisé"
    - "plq"
    - "périmètre de développement"
  equipements:
    - "équipements"
    - "equipements"
    - "centralités"
    - "centralites"
    - "mise en réseau des espaces publics"
  paysage:
    - "paysage"
  risques:
    - "risques"
    - "dangers"
    - "zones instables"
    - "éboulis"
    - "eboulis"
    - "façade exposée"
    - "facade exposee"
    - "bruit"
    - "dba"
  energie:
    - "énergies"
    - "energies"
    - "énergie"
    - "energie"
    - "sondes"
    - "géothermique"
    - "geothermique"
    - "chaudière"
    - "chaudiere"
    - "assainissement"
    - "transition du parc bâti"
    - "transition du parc bati"
    - "téléphonie"
    - "telephonie"
  synthese:
    - "synthèse"
    - "synthese"
    - "carte de synthèse"
    - "plan de synthèse"
