#!/usr/bin/env python3
"""
SAD (Service des autorisations de construire) -- Incremental Import Pipeline

Fetches Geneva construction permit dossiers from the SAD public API and
upserts into bronze."SAD" on lamap_db.

INCREMENTAL STRATEGY:
    - Sort by dateDernierDepot DESC (most recently modified first)
    - Page through results, stop when all records on a page are older than
      the cutoff date (last_acquired_at from command center or 30 days ago)
    - UPSERT all fetched records (full overwrite of all fields)

The SAD API requires:
    1. GET the search page to obtain a session + XSRF token
    2. POST search requests with X-XSRF-TOKEN header
    3. Commune filter uses commune NAME strings (not OFS codes)
    4. Type filter is required

DATA SAFETY:
    - UPSERT only (INSERT ... ON CONFLICT DO UPDATE).
    - Never truncates or deletes existing data.
    - Full field overwrite on update (SAD dossiers evolve over time).

Environment variables:
    RE_LLM_SUPABASE_URL                 - re-LLM Supabase project URL (required)
    RE_LLM_SUPABASE_SERVICE_ROLE_KEY    - re-LLM service_role key     (required)
    RE_LLM_SCHEMA                       - target schema               (default: bronze_ch)
    CAMELOTE_SUPABASE_URL               - Camelote command-center URL (optional)
    CAMELOTE_SUPABASE_KEY               - Camelote service_role key   (optional)

re-LLM is the sole write target. Production data flows lamap_db ← FDW ←
re-LLM via gold_ch.run_sync_proc('daily').
"""

import json
import os
import re
import sys
import time
from datetime import datetime, timedelta, timezone

import requests

# Add repo root to path so we can import shared/
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from shared.supabase_client import batch_upsert
from shared.freshness import get_dataset_meta, update_dataset_meta


# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------

SAD_BASE = "https://app2.ge.ch/sadconsult"
SAD_SEARCH_URL = f"{SAD_BASE}/api/dossier/rechercher"
SAD_COUNT_URL = f"{SAD_BASE}/api/dossier/rechercher/count"
SAD_DECISIONS_URL = f"{SAD_BASE}/api/dossieroac/decisions"
SAD_REFERENTIEL_URL = f"{SAD_BASE}/api/referentiel"
SAD_INIT_URL = f"{SAD_BASE}/recherche/autorisationConstruire"

TABLE = "ge_sad"            # re-LLM bronze_ch.ge_sad
CONFLICT_COLUMN = "type,numero,numero_complementaire"
BATCH_SIZE = 500
PAGE_SIZE = 100
DATASET_CODE = "ge_sad"

# All SAD dossier types
SAD_TYPES = "(APA,MPA,DD,M,DP,APAT,APL,LER,LER-PA,LER-PAT)"

# Default lookback for first run (days)
DEFAULT_LOOKBACK_DAYS = 30

# Fields to exclude (auto-generated by Supabase)
EXCLUDE_COLUMNS = {"id", "created_at", "updated_at", "iteration"}


# ------------------------------------------------------------------
# SAD API session
# ------------------------------------------------------------------

def create_sad_session() -> tuple[requests.Session, str]:
    """
    Create a SAD API session by visiting the search page.
    Returns (session, xsrf_token).
    """
    s = requests.Session()
    r = s.get(SAD_INIT_URL, timeout=30)
    r.raise_for_status()

    xsrf = s.cookies.get("XSRF-TOKEN")
    if not xsrf:
        raise RuntimeError("Could not obtain XSRF token from SAD")

    print(f"  SAD session created (XSRF: {xsrf[:12]}...)")
    return s, xsrf


def sad_headers(xsrf: str) -> dict:
    """Build headers for SAD API requests."""
    return {
        "Content-Type": "application/json",
        "X-XSRF-TOKEN": xsrf,
    }


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def camel_to_snake(name: str) -> str:
    """
    Convert camelCase to snake_case.
    Handles consecutive uppercase (e.g. statutDA → statut_da, not statut_d_a).
    """
    # Insert underscore before uppercase letters that follow a lowercase letter
    s1 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    # Insert underscore between consecutive uppercase and following lowercase
    s2 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s1)
    return s2.lower()


# Explicit field name overrides for SAD API → table column mapping
# These handle cases where camel_to_snake doesn't produce the right result
FIELD_OVERRIDES = {
    "idAutorisation": "id_autorisation",
    "numeroComplementaire": "numero_complementaire",
    "dateStatut": "date_statut",
    "statutDA": "statut_da",
    "dateDepot": "date_depot",
    "dateAcceptation": "date_acceptation",
    "numeroBordereau": "numero_bordereau",
    "proprietaireAdresse": "proprietaire_adresse",
    "mandataireAdresse": "mandataire_adresse",
    "requerantPrincipal": "requerant_principal",
    "requerantPrincipalAdresse": "requerant_principal_adresse",
    "requerantSecondaire": "requerant_secondaire",
    "requerantSecondaireAdresse": "requerant_secondaire_adresse",
    "remarqueDossier": "remarque_dossier",
    "isRemarqueDiffusable": "is_remarque_diffusable",
    "remarqueDA": "remarque_da",
    "isRemarqueDADiffusable": "is_remarque_da_diffusable",
    "codeAmenagement": "code_amenagement",
    "origineDossier": "origine_dossier",
    "codeInstanceDirectrice": "code_instance_directrice",
    "libelleInstanceDirectrice": "libelle_instance_directrice",
    "decisionGlobInstanceDirectrice": "decision_glob_instance_directrice",
    "avisFaoInstanceDirectrice": "avis_fao_instance_directrice",
    "dateFinValidInstanceDirectrice": "date_fin_valid_instance_directrice",
}


def parse_sad_date(date_str: str | None) -> datetime | None:
    """Parse DD.MM.YYYY date string to datetime."""
    if not date_str:
        return None
    try:
        return datetime.strptime(date_str, "%d.%m.%Y")
    except ValueError:
        return None


def get_row_count(url: str, key: str, schema: str, table: str) -> int | None:
    """Get current row count via PostgREST HEAD request."""
    endpoint = f"{url.rstrip('/')}/rest/v1/{table}?select=count"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Prefer": "count=exact",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.head(endpoint, headers=headers, timeout=30)
        cr = r.headers.get("content-range", "")
        if "/" in cr:
            return int(cr.split("/")[1])
    except Exception as e:
        print(f"  Warning: could not get row count: {e}")
    return None


def get_table_columns(url: str, key: str, schema: str, table: str) -> set[str]:
    """Discover existing columns in a table via PostgREST."""
    endpoint = f"{url.rstrip('/')}/rest/v1/{table}?limit=1"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.get(endpoint, headers=headers, timeout=15)
        if r.status_code == 200:
            rows = r.json()
            if rows:
                return set(rows[0].keys())
    except Exception as e:
        print(f"  Warning: could not discover table columns: {e}")
    return set()


def get_most_recent_date(url: str, key: str, schema: str, table: str) -> datetime | None:
    """
    Get the most recent date_statut from the SAD table.
    This serves as the "last modification" marker for incremental fetches.
    """
    endpoint = (
        f"{url.rstrip('/')}/rest/v1/{table}"
        f"?select=date_statut&order=date_statut.desc&limit=1"
    )
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.get(endpoint, headers=headers, timeout=15)
        if r.status_code == 200:
            rows = r.json()
            if rows and rows[0].get("date_statut"):
                ds = rows[0]["date_statut"]
                return parse_sad_date(ds)
    except Exception:
        pass
    return None


# ------------------------------------------------------------------
# SAD API fetching
# ------------------------------------------------------------------

def get_communes(session: requests.Session, xsrf: str) -> list[str]:
    """Fetch the list of commune names from the SAD referentiel."""
    r = session.get(SAD_REFERENTIEL_URL, timeout=15)
    if r.status_code == 200:
        data = r.json()
        if isinstance(data, dict) and "communes" in data:
            return [c["libelle"] for c in data["communes"]]
    # Fallback hardcoded list
    return [
        "Aire-la-Ville", "Anieres", "Avully", "Avusy", "Bardonnex",
        "Bellevue", "Bernex", "Carouge", "Cartigny", "Celigny",
        "Chancy", "Chene-Bougeries", "Chene-Bourg", "Choulex",
        "Collex-Bossy", "Collonge-Bellerive", "Cologny", "Confignon",
        "Corsier", "Dardagny", "Geneve-Cite", "Geneve-Eaux-Vives",
        "Geneve-Petit-Saconnex", "Geneve-Plainpalais", "Genthod",
        "Grand-Saconnex", "Gy", "Hermance", "Jussy", "Laconnex",
        "Lancy", "Meinier", "Meyrin", "Onex", "Perly-Certoux",
        "Plan-les-Ouates", "Pregny-Chambesy", "Presinge", "Puplinge",
        "Russin", "Satigny", "Soral", "Thonex", "Troinex",
        "Vandoeuvres", "Vernier", "Versoix", "Veyrier",
    ]


def get_total_count(
    session: requests.Session, xsrf: str, commune: str = ""
) -> int:
    """Get total record count from SAD API."""
    body = {
        "type": SAD_TYPES,
        "page": 1,
        "lignesParPage": 15,
        "sortBy": "dateDernierDepot",
        "sortDesc": True,
    }
    if commune:
        body["commune"] = commune

    try:
        r = session.post(
            SAD_COUNT_URL, json=body, headers=sad_headers(xsrf), timeout=30
        )
        if r.status_code == 200:
            return int(r.text.strip())
    except Exception:
        pass
    return 0


def fetch_page(
    session: requests.Session,
    xsrf: str,
    commune: str,
    page: int,
    page_size: int = PAGE_SIZE,
) -> list[dict]:
    """Fetch one page of SAD dossiers for a commune."""
    body = {
        "type": SAD_TYPES,
        "commune": commune,
        "page": page,
        "lignesParPage": page_size,
        "sortBy": "dateDernierDepot",
        "sortDesc": True,
    }
    for attempt in range(1, 4):
        try:
            r = session.post(
                SAD_SEARCH_URL, json=body, headers=sad_headers(xsrf), timeout=60
            )
            if r.status_code == 200:
                data = r.json()
                if isinstance(data, list):
                    return data
                return []
            elif r.status_code >= 500:
                wait = 5 * attempt
                print(f"    Server error {r.status_code}, retrying in {wait}s...")
                time.sleep(wait)
            else:
                print(f"    API error {r.status_code}: {r.text[:200]}")
                return []
        except Exception as e:
            wait = 5 * attempt
            print(f"    Request error ({e}), retrying in {wait}s...")
            time.sleep(wait)

    return []


def fetch_decisions(
    session: requests.Session, xsrf: str, business_key: str
) -> list[dict] | None:
    """Fetch decisions for a dossier."""
    url = f"{SAD_DECISIONS_URL}?businessKey={business_key}"
    try:
        r = session.get(url, headers=sad_headers(xsrf), timeout=15)
        if r.status_code == 200:
            data = r.json()
            if isinstance(data, list):
                return data
    except Exception:
        pass
    return None


def transform_record(raw: dict) -> dict:
    """
    Transform a SAD API record to match the bronze table schema.
    Uses explicit field mappings where available, falls back to camelCase→snake_case.
    """
    record = {}
    for k, v in raw.items():
        snake_key = FIELD_OVERRIDES.get(k, camel_to_snake(k))
        # Normalise empty strings to None
        if isinstance(v, str) and not v.strip():
            v = None
        record[snake_key] = v

    # Build the SAD URL
    dtype = record.get("type")
    numero = record.get("numero")
    complement = record.get("numero_complementaire")
    if dtype and numero:
        record["url"] = (
            f"https://app2.ge.ch/sadconsult/dossier/"
            f"{dtype}/{numero}/{complement or '1'}"
        )

    return record


# ------------------------------------------------------------------
# Incremental fetch logic
# ------------------------------------------------------------------

def fetch_incremental(
    session: requests.Session,
    xsrf: str,
    cutoff_date: datetime,
    communes: list[str],
) -> list[dict]:
    """
    Fetch all SAD dossiers modified since cutoff_date.

    Strategy: For each commune, page through results sorted by
    dateDernierDepot DESC. Stop when we hit records whose latest
    date fields (dateStatut, dateDepot) are ALL older than cutoff.
    """
    all_records = []
    cutoff_str = cutoff_date.strftime("%Y-%m-%d")

    print(f"\n  Cutoff date: {cutoff_str}")
    print(f"  Communes: {len(communes)}")

    for ci, commune in enumerate(communes):
        page = 1
        commune_records = 0
        stop_commune = False

        while not stop_commune:
            items = fetch_page(session, xsrf, commune, page)

            if not items:
                break

            page_has_recent = False

            for item in items:
                # Check if this record is recent enough
                # Use dateStatut as the best proxy for "last modified"
                date_statut = parse_sad_date(item.get("dateStatut"))
                date_depot = parse_sad_date(item.get("dateDepot"))
                date_acceptation = parse_sad_date(item.get("dateAcceptation"))

                # Take the most recent date as "last modified"
                dates = [d for d in [date_statut, date_depot, date_acceptation] if d]
                most_recent = max(dates) if dates else None

                if most_recent and most_recent >= cutoff_date:
                    page_has_recent = True

                # Transform and collect record regardless of date
                # (the sort is approximate, so we collect everything
                # on pages that have at least one recent record)
                record = transform_record(item)
                all_records.append(record)
                commune_records += 1

            # If NO records on this page were recent, stop this commune
            if not page_has_recent:
                break

            # If we got fewer results than page size, we've exhausted this commune
            if len(items) < PAGE_SIZE:
                break

            page += 1

            # Small delay between pages
            time.sleep(0.5)

        if commune_records > 0:
            print(f"  [{ci+1}/{len(communes)}] {commune}: {commune_records} records ({page} pages)")

        # Small delay between communes
        time.sleep(0.3)

    return all_records


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

def main():
    rellm_url = os.environ.get("RE_LLM_SUPABASE_URL", "")
    rellm_key = os.environ.get("RE_LLM_SUPABASE_SERVICE_ROLE_KEY", "")
    rellm_schema = os.environ.get("RE_LLM_SCHEMA", "bronze_ch")
    camelote_url = os.environ.get("CAMELOTE_SUPABASE_URL", "")
    camelote_key = os.environ.get("CAMELOTE_SUPABASE_KEY", "")

    if not rellm_url or not rellm_key:
        print("ERROR: RE_LLM_SUPABASE_URL and RE_LLM_SUPABASE_SERVICE_ROLE_KEY are required")
        sys.exit(1)

    print("=" * 60)
    print("  SAD (Construction Permits) Pipeline — Incremental")
    print(f"  Target: {rellm_schema}.{TABLE}")
    print("=" * 60)

    # -- Determine cutoff date --
    meta = get_dataset_meta(camelote_url, camelote_key, DATASET_CODE)
    if meta and meta.get("last_acquired_at"):
        cutoff_date = meta["last_acquired_at"].replace(tzinfo=None)
        print(f"\n  Last acquired: {cutoff_date.isoformat()}")
        print(f"  Previous record count: {meta.get('record_count', 'unknown')}")
    else:
        cutoff_date = datetime.now() - timedelta(days=DEFAULT_LOOKBACK_DAYS)
        print(f"\n  No previous metadata found, using {DEFAULT_LOOKBACK_DAYS}-day lookback")

    print(f"  Cutoff: {cutoff_date.strftime('%Y-%m-%d')}")

    # -- Discover table columns --
    print("\n  Discovering table columns...")
    table_columns = get_table_columns(rellm_url, rellm_key, rellm_schema, TABLE)
    if table_columns:
        allowed = table_columns - EXCLUDE_COLUMNS
        print(f"  Table has {len(table_columns)} columns, {len(allowed)} writable")
    else:
        print("  Warning: Could not discover columns, will send all fields")
        allowed = None

    # -- Row count BEFORE --
    rows_before = get_row_count(rellm_url, rellm_key, rellm_schema, TABLE)
    print(
        f"  Rows before: {rows_before:,}" if rows_before is not None
        else "  Rows before: unknown"
    )

    # -- Create SAD session --
    print("\n  Connecting to SAD API...")
    session, xsrf = create_sad_session()

    # -- Get commune list --
    communes = get_communes(session, xsrf)
    print(f"  Communes: {len(communes)}")

    # -- Get total count --
    total_in_api = get_total_count(session, xsrf)
    print(f"  Total dossiers in SAD: {total_in_api:,}")

    # -- Incremental fetch --
    start_time = time.time()
    print(f"\n{'━' * 60}")
    print("  Fetching modified dossiers...")
    print(f"{'━' * 60}")

    all_records = fetch_incremental(session, xsrf, cutoff_date, communes)

    fetch_elapsed = time.time() - start_time
    print(f"\n  Fetch complete: {len(all_records):,} records in {fetch_elapsed:.0f}s")

    if not all_records:
        print("  No modified dossiers found since cutoff date.")
        # Update metadata anyway to mark successful check
        update_dataset_meta(
            camelote_url, camelote_key, DATASET_CODE,
            record_count=rows_before,
            status="active",
        )
        print("=" * 60)
        return

    # -- Filter to known columns --
    if allowed:
        filtered_records = []
        dropped_cols = set()
        for rec in all_records:
            filtered = {}
            for k, v in rec.items():
                if k in allowed:
                    filtered[k] = v
                else:
                    dropped_cols.add(k)
            filtered_records.append(filtered)
        if dropped_cols:
            print(f"  Dropped unknown columns: {', '.join(sorted(dropped_cols))}")
        all_records = filtered_records

    # -- Normalise keys (all records must have same keys for PostgREST) --
    all_keys = set()
    for r in all_records:
        all_keys |= r.keys()
    for r in all_records:
        for k in all_keys:
            r.setdefault(k, None)

    # -- Upsert --
    print(f"\n  Upserting {len(all_records):,} records (batch size {BATCH_SIZE})...")

    total_upserted = batch_upsert(
        url=rellm_url,
        key=rellm_key,
        table=TABLE,
        records=all_records,
        conflict_column=CONFLICT_COLUMN,
        schema=rellm_schema,
        batch_size=BATCH_SIZE,
    )

    # -- Row count AFTER --
    rows_after = get_row_count(rellm_url, rellm_key, rellm_schema, TABLE)

    # -- Summary --
    elapsed = time.time() - start_time
    net_new = 0
    if rows_before is not None and rows_after is not None:
        net_new = rows_after - rows_before

    print(f"\n{'=' * 60}")
    print("  IMPORT COMPLETE")
    print(f"  Records fetched:  {len(all_records):,}")
    print(f"  Rows upserted:    {total_upserted:,}")
    print(f"  Net new:          {net_new:,}")
    print(f"  Rows before:      {rows_before:,}" if rows_before is not None else "  Rows before:      unknown")
    print(f"  Rows after:       {rows_after:,}" if rows_after is not None else "  Rows after:       unknown")
    print(f"  Duration:         {elapsed / 60:.1f} min")
    print("=" * 60)

    if total_upserted == 0:
        print("  FAILED: Zero rows upserted!")
        sys.exit(1)

    # -- Update dataset metadata --
    update_dataset_meta(
        camelote_url, camelote_key, DATASET_CODE,
        record_count=rows_after,
        status="active",
    )


if __name__ == "__main__":
    main()
