#!/usr/bin/env python3
"""
GWR (Federal Building Register) — Import Pipeline

Downloads the Swiss federal building register (Gebaeude- und Wohnungsregister)
from BFS and upserts into bronze."HOUSING_STATS_BUILDING" on lamap_db.

Source:  https://public.madd.bfs.admin.ch/ch.zip
         → gebaeude_batiment_edificio.csv (tab-delimited, ~3.3M rows)

STREAMING: Processes rows in batches of 1000 to keep memory low.
           Logs progress every 10,000 rows.

DATA SAFETY:
    - UPSERT only (INSERT ... ON CONFLICT DO UPDATE).
    - Never truncates or deletes existing data.
    - Row count should only go UP or stay the same.

Environment variables:
    LAMAP_SUPABASE_URL          - Lamap Supabase project URL (required)
    LAMAP_SUPABASE_SERVICE_KEY  - service_role key (required)
    LAMAP_SCHEMA                - target schema (default: bronze)
"""

import csv
import io
import os
import sys
import time
import zipfile

import requests

# Add repo root to path so we can import shared/
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from shared.supabase_client import batch_upsert


# ──────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────

ZIP_URL = "https://public.madd.bfs.admin.ch/ch.zip"
CSV_FILENAME = "gebaeude_batiment_edificio.csv"
TABLE = "HOUSING_STATS_BUILDING"
CONFLICT_COLUMN = "egid"
BATCH_SIZE = 1000
LOG_EVERY = 10000

# Columns to exclude (auto-generated by Supabase)
EXCLUDE_COLUMNS = {"id", "created_at", "updated_at", "iteration"}


# ──────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────

def get_row_count(url: str, key: str, schema: str, table: str) -> int | None:
    """Get current row count via PostgREST HEAD request."""
    endpoint = f"{url.rstrip('/')}/rest/v1/{table}?select=count"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Prefer": "count=exact",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.head(endpoint, headers=headers, timeout=30)
        cr = r.headers.get("content-range", "")
        if "/" in cr:
            return int(cr.split("/")[1])
    except Exception as e:
        print(f"  Warning: could not get row count: {e}")
    return None


def get_table_columns(url: str, key: str, schema: str, table: str) -> set[str]:
    """Discover existing columns in a table via PostgREST."""
    endpoint = f"{url.rstrip('/')}/rest/v1/{table}?limit=1"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.get(endpoint, headers=headers, timeout=15)
        if r.status_code == 200:
            rows = r.json()
            if rows:
                return set(rows[0].keys())
    except Exception as e:
        print(f"  Warning: could not discover table columns: {e}")
    return set()


# ──────────────────────────────────────────────────────────────
# Download & Extract
# ──────────────────────────────────────────────────────────────

def download_zip() -> io.BytesIO:
    """Download the BFS ZIP file with progress logging."""
    print(f"  Downloading {ZIP_URL} ...")
    r = requests.get(ZIP_URL, stream=True, timeout=30)
    r.raise_for_status()

    total_size = int(r.headers.get("content-length", 0))
    data = io.BytesIO()
    downloaded = 0
    last_log = 0

    for chunk in r.iter_content(chunk_size=1024 * 1024):  # 1 MB chunks
        data.write(chunk)
        downloaded += len(chunk)
        if downloaded - last_log >= 50 * 1024 * 1024:  # Log every 50 MB
            mb = downloaded / (1024 * 1024)
            total_mb = total_size / (1024 * 1024) if total_size else 0
            print(f"    Downloaded {mb:.0f} / {total_mb:.0f} MB")
            last_log = downloaded

    mb = downloaded / (1024 * 1024)
    print(f"  Download complete: {mb:.0f} MB")
    data.seek(0)
    return data


def find_csv_in_zip(zip_data: io.BytesIO) -> str:
    """Find the gebaeude CSV file inside the ZIP archive."""
    z = zipfile.ZipFile(zip_data)
    for name in z.namelist():
        if "gebaeude" in name.lower() and name.endswith(".csv"):
            print(f"  Found: {name}")
            return name
    # Fallback: list all files
    print(f"  ZIP contents: {z.namelist()}")
    raise FileNotFoundError(f"Could not find {CSV_FILENAME} in ZIP archive")


# ──────────────────────────────────────────────────────────────
# Stream & Upsert
# ──────────────────────────────────────────────────────────────

def stream_upsert(
    zip_data: io.BytesIO,
    csv_name: str,
    allowed_columns: set[str],
    url: str,
    key: str,
    schema: str,
) -> tuple[int, int]:
    """
    Stream CSV rows from the ZIP and upsert in batches.
    Returns (total_read, total_upserted).
    """
    z = zipfile.ZipFile(zip_data)

    with z.open(csv_name) as raw:
        # Wrap in TextIOWrapper for csv.DictReader; use utf-8-sig to strip BOM
        text_file = io.TextIOWrapper(raw, encoding="utf-8-sig")
        reader = csv.DictReader(text_file, delimiter="\t")

        buffer = []
        total_read = 0
        total_upserted = 0
        start_time = time.time()

        for row in reader:
            # Lowercase all keys, filter to allowed columns, strip whitespace
            record = {}
            for k, v in row.items():
                col = k.strip().lower()
                if col in allowed_columns:
                    record[col] = (v.strip() if v else None) or None
            buffer.append(record)
            total_read += 1

            if len(buffer) >= BATCH_SIZE:
                # Normalise keys (PGRST102: all objects must have same keys)
                all_keys = set()
                for rec in buffer:
                    all_keys |= rec.keys()
                for rec in buffer:
                    for k in all_keys:
                        rec.setdefault(k, None)

                upserted = batch_upsert(
                    url=url,
                    key=key,
                    table=TABLE,
                    records=buffer,
                    conflict_column=CONFLICT_COLUMN,
                    schema=schema,
                    batch_size=BATCH_SIZE,
                )
                total_upserted += upserted
                buffer = []

            if total_read % LOG_EVERY == 0:
                elapsed = time.time() - start_time
                rate = total_read / elapsed if elapsed > 0 else 0
                print(
                    f"    Progress: {total_read:,} rows read, "
                    f"{total_upserted:,} upserted "
                    f"({rate:.0f} rows/s)"
                )

        # Flush remaining buffer
        if buffer:
            all_keys = set()
            for rec in buffer:
                all_keys |= rec.keys()
            for rec in buffer:
                for k in all_keys:
                    rec.setdefault(k, None)

            upserted = batch_upsert(
                url=url,
                key=key,
                table=TABLE,
                records=buffer,
                conflict_column=CONFLICT_COLUMN,
                schema=schema,
                batch_size=BATCH_SIZE,
            )
            total_upserted += upserted

    return total_read, total_upserted


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────

def main():
    lamap_url = os.environ.get("LAMAP_SUPABASE_URL", "")
    lamap_key = os.environ.get("LAMAP_SUPABASE_SERVICE_KEY", "")
    lamap_schema = os.environ.get("LAMAP_SCHEMA", "bronze")

    if not lamap_url or not lamap_key:
        print("ERROR: LAMAP_SUPABASE_URL and LAMAP_SUPABASE_SERVICE_KEY are required")
        sys.exit(1)

    print("=" * 60)
    print("  GWR (Federal Building Register) Pipeline")
    print(f"  Source: {ZIP_URL}")
    print(f"  Target: {lamap_schema}.{TABLE}")
    print("=" * 60)

    # ── Discover table columns ──
    print("\n  Discovering table columns...")
    table_columns = get_table_columns(lamap_url, lamap_key, lamap_schema, TABLE)
    if not table_columns:
        print("  ERROR: Could not discover table columns")
        sys.exit(1)

    allowed = table_columns - EXCLUDE_COLUMNS
    print(f"  Table has {len(table_columns)} columns, {len(allowed)} writable")

    # ── Row count BEFORE ──
    rows_before = get_row_count(lamap_url, lamap_key, lamap_schema, TABLE)
    print(f"  Rows before: {rows_before:,}" if rows_before is not None else "  Rows before: unknown")

    # ── Download ZIP ──
    zip_data = download_zip()

    # ── Find CSV ──
    csv_name = find_csv_in_zip(zip_data)

    # ── Stream & Upsert ──
    print(f"\n  Streaming {csv_name} → {lamap_schema}.{TABLE}")
    print(f"  Batch size: {BATCH_SIZE}, logging every {LOG_EVERY:,} rows")
    print(f"{'━' * 60}")

    start = time.time()
    total_read, total_upserted = stream_upsert(
        zip_data=zip_data,
        csv_name=csv_name,
        allowed_columns=allowed,
        url=lamap_url,
        key=lamap_key,
        schema=lamap_schema,
    )
    elapsed = time.time() - start

    # ── Row count AFTER ──
    rows_after = get_row_count(lamap_url, lamap_key, lamap_schema, TABLE)

    # ── Summary ──
    print(f"\n{'=' * 60}")
    print("  IMPORT COMPLETE")
    print(f"  CSV rows read:    {total_read:,}")
    print(f"  Rows upserted:    {total_upserted:,}")
    print(f"  Rows before:      {rows_before:,}" if rows_before is not None else "  Rows before:      unknown")
    print(f"  Rows after:       {rows_after:,}" if rows_after is not None else "  Rows after:       unknown")
    if rows_before is not None and rows_after is not None:
        delta = rows_after - rows_before
        print(f"  Net new:          {delta:,}")
        if rows_after < rows_before:
            print("  WARNING: Row count DECREASED!")
    print(f"  Duration:         {elapsed / 60:.1f} min")
    print("=" * 60)

    if total_upserted == 0:
        print("  FAILED: Zero rows upserted!")
        sys.exit(1)


if __name__ == "__main__":
    main()
