#!/usr/bin/env python3
"""
GWR (Federal Building Register) — Import Pipeline

Downloads the Swiss federal building register (Gebaeude- und Wohnungsregister)
from BFS and upserts BOTH files it contains into re-LLM bronze_ch:

Source:  https://public.madd.bfs.admin.ch/ch.zip  (ONE delivery, ~944 MB)
         → gebaeude_batiment_edificio.csv  (~3.3M rows) → bfs_rebl_buildings  (key EGID)
         → wohnung_logement_abitazione.csv (~5.3M rows) → bfs_rebl_housing    (key EGID+EWID)

The dwelling file carries WAREA (measured habitable surface), WAZIM, WSTWK, WSTAT
and WMEHRG, and feeds gold_ch.building_dwelling_areas → lamap ref.building_dwelling_areas.

(EGID, EWID) is the dwelling key and is unique in the source — a maisonette
(WMEHRG=1) is ONE row, not one per floor. Do not add de-duplication here; it would
break that guarantee. Each dataset is stamped individually via its own code, never
by workflow_file.

STREAMING: Processes rows in batches of 1000 to keep memory low.
           Logs progress every 10,000 rows.

DATA SAFETY:
    - UPSERT only (INSERT ... ON CONFLICT DO UPDATE).
    - Never truncates or deletes existing data.
    - Row count should only go UP or stay the same.

Environment variables:
    RE_LLM_SUPABASE_URL              - re-LLM Supabase project URL (required)
    RE_LLM_SUPABASE_SERVICE_ROLE_KEY - service_role key (required)
    RE_LLM_SCHEMA                    - target schema (default: bronze_ch)
"""

import csv
import io
import os
import sys
import time
import zipfile

import requests

# Add repo root to path so we can import shared/
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from shared.supabase_client import batch_upsert
from shared.freshness import source_modified_since, get_dataset_meta, update_dataset_meta


# ──────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────

ZIP_URL = "https://public.madd.bfs.admin.ch/ch.zip"
BATCH_SIZE = 1000
LOG_EVERY = 10000

# Explicit manifest — one entry per target table this workflow writes.
# scripts/check_dataset_registration.py reads pipelines/gwr/datasets.json (kept in
# sync with this list) so a workflow with N targets must have N registered datasets.
DATASETS = [
    {
        "code": "ch_bfs_housing_building",
        "table": "bfs_rebl_buildings",
        "csv_match": "gebaeude",
        "conflict": "egid",
    },
    {
        "code": "ch_bfs_rebl_housing",
        "table": "bfs_rebl_housing",
        "csv_match": "wohnung",
        # Must match the EXISTING unique index idx_bfs_rebl_housing_unique
        # (egid, ewid, edid) or PostgREST has no constraint to upsert against.
        # (egid,ewid) is already unique in the data, so including edid changes no
        # collision behaviour — row identity is preserved, no de-duplication added.
        "conflict": "egid,ewid,edid",
    },
]

# Columns to exclude (auto-generated by Supabase)
EXCLUDE_COLUMNS = {"id", "created_at", "updated_at", "iteration"}


# ──────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────

def get_row_count(url: str, key: str, schema: str, table: str) -> int | None:
    """Get current row count via PostgREST HEAD request."""
    endpoint = f"{url.rstrip('/')}/rest/v1/{table}?select=count"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Prefer": "count=exact",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.head(endpoint, headers=headers, timeout=30)
        cr = r.headers.get("content-range", "")
        if "/" in cr:
            return int(cr.split("/")[1])
    except Exception as e:
        print(f"  Warning: could not get row count: {e}")
    return None


def get_table_columns(url: str, key: str, schema: str, table: str) -> set[str]:
    """Discover existing columns in a table via PostgREST."""
    endpoint = f"{url.rstrip('/')}/rest/v1/{table}?limit=1"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
    }
    if schema and schema != "public":
        headers["Accept-Profile"] = schema
    try:
        r = requests.get(endpoint, headers=headers, timeout=15)
        if r.status_code == 200:
            rows = r.json()
            if rows:
                return set(rows[0].keys())
    except Exception as e:
        print(f"  Warning: could not discover table columns: {e}")
    return set()


# ──────────────────────────────────────────────────────────────
# Download & Extract
# ──────────────────────────────────────────────────────────────

def download_zip() -> io.BytesIO:
    """Download the BFS ZIP file with progress logging."""
    print(f"  Downloading {ZIP_URL} ...")
    r = requests.get(ZIP_URL, stream=True, timeout=30)
    r.raise_for_status()

    total_size = int(r.headers.get("content-length", 0))
    data = io.BytesIO()
    downloaded = 0
    last_log = 0

    for chunk in r.iter_content(chunk_size=1024 * 1024):  # 1 MB chunks
        data.write(chunk)
        downloaded += len(chunk)
        if downloaded - last_log >= 50 * 1024 * 1024:  # Log every 50 MB
            mb = downloaded / (1024 * 1024)
            total_mb = total_size / (1024 * 1024) if total_size else 0
            print(f"    Downloaded {mb:.0f} / {total_mb:.0f} MB")
            last_log = downloaded

    mb = downloaded / (1024 * 1024)
    print(f"  Download complete: {mb:.0f} MB")
    data.seek(0)
    return data


def find_csv_in_zip(zip_data: io.BytesIO, match: str) -> str:
    """Find the CSV whose filename contains `match` inside the ZIP archive."""
    z = zipfile.ZipFile(zip_data)
    for name in z.namelist():
        if match in name.lower() and name.endswith(".csv"):
            print(f"  Found: {name}")
            return name
    print(f"  ZIP contents: {z.namelist()}")
    raise FileNotFoundError(f"Could not find a '{match}*.csv' in ZIP archive")


# ──────────────────────────────────────────────────────────────
# Stream & Upsert
# ──────────────────────────────────────────────────────────────

def stream_upsert(
    zip_data: io.BytesIO,
    csv_name: str,
    allowed_columns: set[str],
    url: str,
    key: str,
    schema: str,
    table: str,
    conflict_column: str,
) -> tuple[int, int]:
    """
    Stream CSV rows from the ZIP and upsert in batches.
    Returns (total_read, total_upserted).
    """
    z = zipfile.ZipFile(zip_data)

    with z.open(csv_name) as raw:
        # Wrap in TextIOWrapper for csv.DictReader; use utf-8-sig to strip BOM
        text_file = io.TextIOWrapper(raw, encoding="utf-8-sig")
        reader = csv.DictReader(text_file, delimiter="\t")

        buffer = []
        total_read = 0
        total_upserted = 0
        start_time = time.time()

        for row in reader:
            # Lowercase all keys, filter to allowed columns, strip whitespace
            record = {}
            for k, v in row.items():
                col = k.strip().lower()
                if col in allowed_columns:
                    record[col] = (v.strip() if v else None) or None
            buffer.append(record)
            total_read += 1

            if len(buffer) >= BATCH_SIZE:
                # Normalise keys (PGRST102: all objects must have same keys)
                all_keys = set()
                for rec in buffer:
                    all_keys |= rec.keys()
                for rec in buffer:
                    for k in all_keys:
                        rec.setdefault(k, None)

                upserted = batch_upsert(
                    url=url,
                    key=key,
                    table=table,
                    records=buffer,
                    conflict_column=conflict_column,
                    schema=schema,
                    batch_size=BATCH_SIZE,
                )
                total_upserted += upserted
                buffer = []

            if total_read % LOG_EVERY == 0:
                elapsed = time.time() - start_time
                rate = total_read / elapsed if elapsed > 0 else 0
                print(
                    f"    Progress: {total_read:,} rows read, "
                    f"{total_upserted:,} upserted "
                    f"({rate:.0f} rows/s)"
                )

        # Flush remaining buffer
        if buffer:
            all_keys = set()
            for rec in buffer:
                all_keys |= rec.keys()
            for rec in buffer:
                for k in all_keys:
                    rec.setdefault(k, None)

            upserted = batch_upsert(
                url=url,
                key=key,
                table=table,
                records=buffer,
                conflict_column=conflict_column,
                schema=schema,
                batch_size=BATCH_SIZE,
            )
            total_upserted += upserted

    return total_read, total_upserted


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────

def process_dataset(ds: dict, zip_data: io.BytesIO, url: str, key: str, schema: str,
                    cam_url: str, cam_key: str) -> bool:
    """Load one CSV from the shared ZIP into its own table and stamp its OWN dataset."""
    table, code = ds["table"], ds["code"]
    print(f"\n{'=' * 60}")
    print(f"  {code}  ->  {schema}.{table}")
    print("=" * 60)

    table_columns = get_table_columns(url, key, schema, table)
    if not table_columns:
        print(f"  ERROR: could not discover columns for {table}")
        return False
    allowed = table_columns - EXCLUDE_COLUMNS
    print(f"  {len(table_columns)} columns, {len(allowed)} writable")

    rows_before = get_row_count(url, key, schema, table)
    print(f"  Rows before: {rows_before:,}" if rows_before is not None else "  Rows before: unknown")

    csv_name = find_csv_in_zip(zip_data, ds["csv_match"])
    start = time.time()
    total_read, total_upserted = stream_upsert(
        zip_data=zip_data, csv_name=csv_name, allowed_columns=allowed,
        url=url, key=key, schema=schema,
        table=table, conflict_column=ds["conflict"],
    )
    elapsed = time.time() - start
    rows_after = get_row_count(url, key, schema, table)

    print(f"\n  read={total_read:,} upserted={total_upserted:,} "
          f"before={rows_before} after={rows_after} in {elapsed / 60:.1f} min")
    if rows_before is not None and rows_after is not None and rows_after < rows_before:
        print("  WARNING: row count DECREASED")
    if total_upserted == 0:
        print(f"  FAILED: zero rows upserted for {code}")
        return False

    # PER-DATASET stamp. Never workflow_file: this workflow writes two tables, and a
    # blanket stamp would mark one of them fresh on the strength of the other's run.
    update_dataset_meta(cam_url, cam_key, code, record_count=rows_after, status="active")
    print(f"  stamped datasets?code=eq.{code}")
    return True


def main():
    rellm_url = os.environ.get("RE_LLM_SUPABASE_URL", "")
    rellm_key = os.environ.get("RE_LLM_SUPABASE_SERVICE_ROLE_KEY", "")
    rellm_schema = os.environ.get("RE_LLM_SCHEMA", "bronze_ch")
    camelote_url = os.environ.get("CAMELOTE_SUPABASE_URL", "")
    camelote_key = os.environ.get("CAMELOTE_SUPABASE_KEY", "")
    only = os.environ.get("GWR_ONLY", "").strip()

    if not rellm_url or not rellm_key:
        print("ERROR: RE_LLM_SUPABASE_URL and RE_LLM_SUPABASE_SERVICE_ROLE_KEY are required")
        sys.exit(1)

    targets = [d for d in DATASETS if not only or d["code"] == only]
    if not targets:
        print(f"ERROR: GWR_ONLY={only!r} matched no dataset")
        sys.exit(1)

    print("=" * 60)
    print("  GWR (Federal Building + Dwelling Register) Pipeline")
    print(f"  Source: {ZIP_URL}")
    print(f"  Datasets: {', '.join(d['code'] for d in targets)}")
    print("=" * 60)

    # Freshness pre-check against the BUILDING dataset (both files ship in one ZIP,
    # so one Last-Modified check governs the whole delivery).
    meta = get_dataset_meta(camelote_url, camelote_key, DATASETS[0]["code"])
    if meta and meta.get("last_acquired_at") and not only:
        print(f"\n  Last acquired: {meta['last_acquired_at'].isoformat()}")
        if not source_modified_since(ZIP_URL, meta["last_acquired_at"]):
            print("\n  No update needed — source unchanged since last import.")
            return

    zip_data = download_zip()

    failed = []
    for ds in targets:
        try:
            if not process_dataset(ds, zip_data, rellm_url, rellm_key, rellm_schema,
                                   camelote_url, camelote_key):
                failed.append(ds["code"])
        except Exception as e:  # noqa: BLE001
            print(f"  FAILED {ds['code']}: {e}")
            failed.append(ds["code"])

    if failed:
        print(f"\nFAILED datasets: {failed}")
        sys.exit(1)
    print("\nAll datasets imported.")


if __name__ == "__main__":
    main()
