                                                                                                                                                   query                                                                                                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE MATERIALIZED VIEW gold_ch.core_plots AS                                                                                                                                                                                                                                                           +
 WITH bldg_summary AS (                                                                                                                                                                                                                                                                                   +
   SELECT cadastral_buildings.egrid,                                                                                                                                                                                                                                                                      +
     count(*)::integer AS building_count,                                                                                                                                                                                                                                                                 +
     sum(cadastral_buildings.dwelling_count)::integer AS dwelling_count,                                                                                                                                                                                                                                  +
     min(cadastral_buildings.construction_year) AS construction_year_oldest,                                                                                                                                                                                                                              +
     max(cadastral_buildings.construction_year) AS construction_year_newest,                                                                                                                                                                                                                              +
     max(cadastral_buildings.floors_above_ground) AS max_floors,                                                                                                                                                                                                                                          +
     sum(cadastral_buildings.footprint_m2) AS footprint_total_m2,                                                                                                                                                                                                                                         +
     sum(cadastral_buildings.volume_m3) AS volume_total_m3,                                                                                                                                                                                                                                               +
     mode() WITHIN GROUP (ORDER BY cadastral_buildings.category_label) AS primary_category,                                                                                                                                                                                                               +
     mode() WITHIN GROUP (ORDER BY cadastral_buildings.class_label) AS primary_class,                                                                                                                                                                                                                     +
     mode() WITHIN GROUP (ORDER BY cadastral_buildings.heater_energy_1_label) AS primary_heater_energy                                                                                                                                                                                                    +
    FROM silver_ch.cadastral_buildings                                                                                                                                                                                                                                                                    +
   WHERE cadastral_buildings.egrid IS NOT NULL AND cadastral_buildings.egrid <> ''                                                                                                                                                                                                                        +
   GROUP BY cadastral_buildings.egrid                                                                                                                                                                                                                                                                     +
 ), first_addr AS (                                                                                                                                                                                                                                                                                       +
   SELECT DISTINCT ON (b.egrid) b.egrid,                                                                                                                                                                                                                                                                  +
     e.street_name || COALESCE(' ' || e.street_number, '') AS main_address,                                                                                                                                                                                                                               +
     e.postal_code AS main_postal_code,                                                                                                                                                                                                                                                                   +
     e.locality AS main_locality                                                                                                                                                                                                                                                                          +
    FROM silver_ch.cadastral_buildings b                                                                                                                                                                                                                                                                  +
      JOIN silver_ch.cadastral_entrances e ON e.egid::text = b.egid::text                                                                                                                                                                                                                                 +
   WHERE b.egrid IS NOT NULL AND b.egrid <> '' AND e.street_name IS NOT NULL                                                                                                                                                                                                                              +
   ORDER BY b.egrid, e.is_official DESC NULLS LAST, e.edid                                                                                                                                                                                                                                                +
 ), addr_agg AS (                                                                                                                                                                                                                                                                                         +
   SELECT b.egrid,                                                                                                                                                                                                                                                                                        +
     array_agg(DISTINCT ((((e.street_name || COALESCE(' ' || e.street_number, '')) || ', ') || e.postal_code) || ' ') || e.locality) AS addresses,                                                                                                                                                        +
     string_agg(DISTINCT ((((e.street_name || COALESCE(' ' || e.street_number, '')) || ', ') || e.postal_code) || ' ') || e.locality, ' | ') AS addresses_display                                                                                                                                         +
    FROM silver_ch.cadastral_buildings b                                                                                                                                                                                                                                                                  +
      JOIN silver_ch.cadastral_entrances e ON e.egid::text = b.egid::text                                                                                                                                                                                                                                 +
   WHERE b.egrid IS NOT NULL AND b.egrid <> '' AND e.street_name IS NOT NULL                                                                                                                                                                                                                              +
   GROUP BY b.egrid                                                                                                                                                                                                                                                                                       +
 ), bldg_json AS (                                                                                                                                                                                                                                                                                        +
   SELECT b.egrid,                                                                                                                                                                                                                                                                                        +
     jsonb_agg(jsonb_build_object('egid', b.egid, 'category', b.category_label, 'class', b.class_label, 'construction_year', b.construction_year, 'floors', b.floors_above_ground, 'dwellings', b.dwelling_count, 'footprint_m2', b.footprint_m2, 'volume_m3', b.volume_m3) ORDER BY b.egid) AS buildings,+
     string_agg(DISTINCT COALESCE(b.category_label, 'unknown'::character varying)::text, ', ') AS buildings_summary                                                                                                                                                                                       +
    FROM silver_ch.cadastral_buildings b                                                                                                                                                                                                                                                                  +
   WHERE b.egrid IS NOT NULL AND b.egrid <> ''                                                                                                                                                                                                                                                            +
   GROUP BY b.egrid                                                                                                                                                                                                                                                                                       +
 ), owner_agg AS (                                                                                                                                                                                                                                                                                        +
   SELECT lo.egrid,                                                                                                                                                                                                                                                                                       +
     count(*)::integer AS owner_count,                                                                                                                                                                                                                                                                    +
     string_agg(lo.owner_name::text, ' | ' ORDER BY (lo.owner_name::text)) FILTER (WHERE lo.rn <= 3) AS owners_display,                                                                                                                                                                                   +
     jsonb_agg(jsonb_build_object('name', lo.owner_name, 'entity_id', lo.entity_id, 'dob', lo.date_of_birth, 'type', lo.ownership_type) ORDER BY lo.owner_name) AS owners,                                                                                                                                +
     string_agg(lo.owner_name::text, ' ') AS owner_names_search                                                                                                                                                                                                                                           +
    FROM ( SELECT link_plot_owners.egrid,                                                                                                                                                                                                                                                                 +
             link_plot_owners.entity_id,                                                                                                                                                                                                                                                                  +
             link_plot_owners.owner_name,                                                                                                                                                                                                                                                                 +
             link_plot_owners.owner_name_normalized,                                                                                                                                                                                                                                                      +
             link_plot_owners.date_of_birth,                                                                                                                                                                                                                                                              +
             link_plot_owners.head_office,                                                                                                                                                                                                                                                                +
             link_plot_owners.ownership_type,                                                                                                                                                                                                                                                             +
             link_plot_owners.ownership_share,                                                                                                                                                                                                                                                            +
             link_plot_owners.source_table,                                                                                                                                                                                                                                                               +
             row_number() OVER (PARTITION BY link_plot_owners.egrid ORDER BY link_plot_owners.owner_name) AS rn                                                                                                                                                                                           +
            FROM silver_ch.link_plot_owners) lo                                                                                                                                                                                                                                                           +
   GROUP BY lo.egrid                                                                                                                                                                                                                                                                                      +
 ), tx_agg AS (                                                                                                                                                                                                                                                                                           +
   SELECT lt.egrid,                                                                                                                                                                                                                                                                                       +
     max(t.transaction_date) AS last_transaction_date,                                                                                                                                                                                                                                                    +
     (array_agg(t.price ORDER BY t.transaction_date DESC NULLS LAST))[1] AS last_transaction_price,                                                                                                                                                                                                       +
     (array_agg(t.transaction_type ORDER BY t.transaction_date DESC NULLS LAST))[1] AS last_transaction_type                                                                                                                                                                                              +
    FROM silver_ch.link_plot_transactions lt                                                                                                                                                                                                                                                              +
      JOIN silver_ch.event_transactions t ON t.transaction_id::text = lt.transaction_id::text                                                                                                                                                                                                             +
   GROUP BY lt.egrid                                                                                                                                                                                                                                                                                      +
 ), sad_agg AS (                                                                                                                                                                                                                                                                                          +
   SELECT link_plot_sad.egrid,                                                                                                                                                                                                                                                                            +
     count(*)::integer AS sad_count                                                                                                                                                                                                                                                                       +
    FROM silver_ch.link_plot_sad                                                                                                                                                                                                                                                                          +
   GROUP BY link_plot_sad.egrid                                                                                                                                                                                                                                                                           +
 ), listing_agg AS (                                                                                                                                                                                                                                                                                      +
   SELECT ll.egrid,                                                                                                                                                                                                                                                                                       +
     count(*)::integer AS active_listing_count                                                                                                                                                                                                                                                            +
    FROM silver_ch.link_plot_listings ll                                                                                                                                                                                                                                                                  +
      JOIN silver_ch.listing_active la_1 ON la_1.listing_id = ll.listing_id AND la_1.is_active = true                                                                                                                                                                                                     +
   GROUP BY ll.egrid                                                                                                                                                                                                                                                                                      +
 )                                                                                                                                                                                                                                                                                                        +
 SELECT p.egrid,                                                                                                                                                                                                                                                                                          +
     p.canton_code,                                                                                                                                                                                                                                                                                       +
     p.canton_name,                                                                                                                                                                                                                                                                                       +
     p.commune_bfs,                                                                                                                                                                                                                                                                                       +
     p.commune_name,                                                                                                                                                                                                                                                                                      +
     -- NEW (Session 21, 2026-04-29): GIREC sub-sector enrichment for GE plots.                                                                                                                                                                                                                           +
     -- LEFT JOIN to silver_ch.plot_girec; NULL outside GE or for plots not contained in any GIREC polygon (~0.08% on water/border).                                                                                                                                                                      +
     pg.gi_rec_numero,                                                                                                                                                                                                                                                                                    +
     pg.sous_secteur_nom,                                                                                                                                                                                                                                                                                 +
     p.parcel_number,                                                                                                                                                                                                                                                                                     +
     p.surface_m2,                                                                                                                                                                                                                                                                                        +
     p.geometry,                                                                                                                                                                                                                                                                                          +
     p.centroid,                                                                                                                                                                                                                                                                                          +
     p.lv95_e,                                                                                                                                                                                                                                                                                            +
     p.lv95_n,                                                                                                                                                                                                                                                                                            +
     p.wgs84_lat,                                                                                                                                                                                                                                                                                         +
     p.wgs84_lng,                                                                                                                                                                                                                                                                                         +
     COALESCE(bs.building_count, 0) AS building_count,                                                                                                                                                                                                                                                    +
     COALESCE(bs.dwelling_count, 0) AS dwelling_count,                                                                                                                                                                                                                                                    +
     bs.construction_year_oldest,                                                                                                                                                                                                                                                                         +
     bs.construction_year_newest,                                                                                                                                                                                                                                                                         +
     bs.max_floors,                                                                                                                                                                                                                                                                                       +
     bs.footprint_total_m2,                                                                                                                                                                                                                                                                               +
     bs.volume_total_m3,                                                                                                                                                                                                                                                                                  +
     bs.primary_category,                                                                                                                                                                                                                                                                                 +
     bs.primary_class,                                                                                                                                                                                                                                                                                    +
     bs.primary_heater_energy,                                                                                                                                                                                                                                                                            +
     fa.main_address,                                                                                                                                                                                                                                                                                     +
     fa.main_postal_code,                                                                                                                                                                                                                                                                                 +
     fa.main_locality,                                                                                                                                                                                                                                                                                    +
     aa.addresses,                                                                                                                                                                                                                                                                                        +
     aa.addresses_display,                                                                                                                                                                                                                                                                                +
     (((((COALESCE(fa.main_address, '') || ' ') || COALESCE(fa.main_locality, '')) || ' ') || COALESCE(p.parcel_number, '')) || ' ') || COALESCE(p.egrid, '') AS address_search,                                                                                                                          +
     bj.buildings,                                                                                                                                                                                                                                                                                        +
     bj.buildings_summary,                                                                                                                                                                                                                                                                                +
     (((((((COALESCE(fa.main_address, '') || ' ') || COALESCE(fa.main_locality, '')) || ' ') || COALESCE(p.parcel_number, '')) || ' ') || COALESCE(p.egrid, '')) || ' ') || COALESCE(oa.owner_names_search, '') AS search_all,                                                                            +
     COALESCE(oa.owner_count, 0) AS owner_count,                                                                                                                                                                                                                                                          +
     oa.owners_display,                                                                                                                                                                                                                                                                                   +
     oa.owners,                                                                                                                                                                                                                                                                                           +
     oa.owner_names_search,                                                                                                                                                                                                                                                                               +
     ta.last_transaction_date,                                                                                                                                                                                                                                                                            +
     ta.last_transaction_price,                                                                                                                                                                                                                                                                           +
     ta.last_transaction_type,                                                                                                                                                                                                                                                                            +
     COALESCE(la.active_listing_count, 0) AS active_listing_count,                                                                                                                                                                                                                                        +
     COALESCE(sa.sad_count, 0) AS sad_count,                                                                                                                                                                                                                                                              +
     now() AS updated_at                                                                                                                                                                                                                                                                                  +
    FROM silver_ch.cadastral_plots p                                                                                                                                                                                                                                                                      +
      LEFT JOIN bldg_summary bs ON bs.egrid = p.egrid                                                                                                                                                                                                                                                     +
      LEFT JOIN first_addr fa ON fa.egrid = p.egrid                                                                                                                                                                                                                                                       +
      LEFT JOIN addr_agg aa ON aa.egrid = p.egrid                                                                                                                                                                                                                                                         +
      LEFT JOIN bldg_json bj ON bj.egrid = p.egrid                                                                                                                                                                                                                                                        +
      LEFT JOIN owner_agg oa ON oa.egrid = p.egrid                                                                                                                                                                                                                                                        +
      LEFT JOIN tx_agg ta ON ta.egrid = p.egrid                                                                                                                                                                                                                                                           +
      LEFT JOIN sad_agg sa ON sa.egrid = p.egrid                                                                                                                                                                                                                                                          +
      LEFT JOIN listing_agg la ON la.egrid = p.egrid                                                                                                                                                                                                                                                      +
      LEFT JOIN silver_ch.plot_girec pg ON pg.egrid = p.egrid
(1 row)

